# Lecture 3: Style and numpy

## Attribution
- This lecture has been adapted from:
    - The Python lectures delivered by [Mike Gelbart](https://personal.math.ubc.ca/~pwalls/) and are available publicly [here](https://www.youtube.com/watch?v=yBAYduexjuA).

## Lecture 3 Outline:

- **Functions as a data type** 
- **Anonymous functions** 
- **Exceptions, try/except** 
- **Style guides and coding style** 
- **Python debugger (pdb)** 
- **Numpy arrays** 
- **Numpy array shapes** 
- **Numpy indexing and slicing** 
- <span style="color:red">Exercises</span>


In [1]:
from random import random
import pdb
import numpy as np

### Functions as  a data type
- In Python, functions are a data type just like anything else. 
- We often say functions are "first-class objects".

In [3]:
def do_nothing(x):
    return x

In [35]:
type(do_nothing)
x=np.random.randint(10,size=(4,6))
print(x)
np.sort(x, axis=None)

[[5 8 6 3 7 6]
 [3 1 7 3 8 0]
 [2 7 1 6 2 8]
 [2 3 8 4 3 3]]


array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 5, 6, 6, 6, 7, 7, 7, 8, 8,
       8, 8])

In [4]:
print(do_nothing)

<function do_nothing at 0x7f69401eedd0>


In [ ]:
# We can overwrite the function and it will not be a function anymore.
# do_nothing = 5

This means you can pass functions as arguments into other functions.

In [10]:
def square(y):
    return y**2

def evaluate_function_on_x_plus_1(fun, x):
    return fun(x+1)

In [ ]:
evaluate_function_on_x_plus_1(square, 5)

- Above: what happened here?
  - `fun(x+1)` becomes `square(5+1)`
  - `square(6)` becomes `36`

- (optional) You can also write functions that return functions, or define functions inside of other functions.
  - We will not see these often.
  - But they are important ideas in software engineering.

You can end up with pretty weird stuff:

In [6]:
do_nothing(do_nothing)

<function __main__.do_nothing(x)>

In [7]:
do_nothing(do_nothing)(5)

5

Above: 

- First we call `do_nothing(do_nothing)`, which returns the function `do_nothing`
- Then we call `do_nothing(5)` which returns `5`.

In [5]:
do_nothing(do_nothing(5))

5

Above: 

- First we call `do_nothing(5)`, which returns `5`.
- Then we again call `do_nothing(5)`, which returns `5`.

## Anonymous functions (5 min)

There are two ways to define functions in Python:

In [ ]:
def add_one(x):
    return x+1

In [ ]:
add_one(7.2)

In [1]:
add_one = lambda x: x+1 

In [ ]:
type(add_one)

In [2]:
add_one(7.2)

8.2

The two approaches above are identical. The one with `lambda` is called an **anonymous function**.

Some differences:

- anonymous functions can only take up one line of code, so they aren't appropriate in most cases.
- anonymous functions evaluate to a function (remember, functions are first-class objects) immediate, so we can do weird stuff with them.

In [3]:
(lambda x,y: x+y)(6,7)

13

In [11]:
evaluate_function_on_x_plus_1(lambda x: x**2, 5)

36

Above:

- First, `lambda x: x**2` evaluates to a value of type `function`
  - Notice that this function is never given a name - hence "anonymous functions" !
- Then, the function and the integer `5` are passed into `evaluate_function_on_x_plus_1`
- At which point the anonymous function is evaluated on `5+1`, and we get `36`.

## Exceptions, `try`/`except` (10 min)

- If something goes wrong, we don't want the code to crash - we want it to **fail gracefully**.
- In Python, this can be accomplished using `try`/`except`:
- Here is a basic example:

In [12]:
this_variable_does_not_exist

NameError: name 'this_variable_does_not_exist' is not defined

In [13]:
try:
    this_variable_does_not_exist
except:
#     pass
    print("You did something bad!")

You did something bad!


- Python tries to execute the code in the `try` block.
- If an error is encountered, we "catch" this in the `except` block (also called `try`/`catch` in other languages).
- There are many different error types, or **exceptions** - we saw `NameError` above. 

In [ ]:
5/0

In [ ]:
my_list = [1,2,3]
my_list[5]

In [14]:
# (note: this is also valid syntax, just very confusing)
[1,2,3][5]

IndexError: list index out of range

In [ ]:
my_tuple = (1,2,3)
my_tuple[0] = 0

- Ok, so there are apparently a bunch of different errors one could run into. 
- With `try`/`except` you can also catch the exception itself:

In [15]:
try:
    this_variable_does_not_exist
except Exception as ex:
    print("You did something bad!")
    print(ex)
    print(type(ex))

You did something bad!
name 'this_variable_does_not_exist' is not defined
<class 'NameError'>


- In the above, we caught the exception and assigned it to the variable `ex` so that we could print it out.
- This is useful because you can see what the error message would have been, without crashing your program.

- You can also catch specific exceptions types, like so:

In [ ]:
try:
    this_variable_does_not_exist
except TypeError:
    print("You made a type error!")
except NameError:
    print("You made a name error!")
except:
    print("You made some other sort of error")

- The final `except` would trigger if the error is none of the above types, so this sort of has an `if`/`elif`/`else` feel to it. 
- There are some extra features, in particular an `else` and `finally` block; if you are interested, see e.g., [here](https://www.w3schools.com/python/python_try_except.asp).

In [19]:
try:
    5/0
except TypeError:
    print("You made a type error!")
except NameError:
    print("You made a name error!")
except Exception as ex:
    print("You made some other sort of error")

You made some other sort of error


- Ideally, try to make your `try`/`except` blocks specific, and try not to put more errors inside the `except`... 

In [20]:
try:
    this_variable_does_not_exist
except:
    5/0

ZeroDivisionError: division by zero

- This is a bit much, but it does happen sometimes :(

#### Using `raise`

- You can also write code that raises an exception on purpose, using `raise`

In [21]:
def add_one(x):
    return x+1

In [22]:
add_one("blah")

TypeError: can only concatenate str (not "int") to str

In [24]:
def add_one(x):
    if not isinstance(x, float) and not isinstance(x, int):
        raise Exception("Sorry, x must be numeric")
        
    return x+1

In [25]:
add_one("blah")

Exception: Sorry, x must be numeric

- This is useful when your function is complicated and would fail in a complicated way, with a weird error message.
- You can make the cause of the error much clearer to the _caller_ of the function.
- Thus, your function is more usable this way.
- If you do this, you should ideally describe these exceptions in the function documentation, so a user knows what to expect if they call your function.  

- You can also raise other types of exceptions, or even define your own exception types, as in lab 2.
- You can also use `raise` by itself to raise whatever exception was going on:

In [26]:
try:
    this_variable_does_not_exist
except:
    print("You did something bad!")
    raise

You did something bad!


NameError: name 'this_variable_does_not_exist' is not defined

- Here, the original exception is raised after we ran some other code.

## Style guides and coding style (15 min)

- It is incorrect to think that if code works then you are done.
- Code has two "users" - the computer (which turns it into machine instructions) and humans, who will likely read and/or modify the code in the future.
- This section is about how to make your code suitable to that second audience, humans.



#### What is style?

- We already talked about the DRY principle

Today we will talk about:
  - variable names
  - magic numbers
  - comments
  - whitespace

#### Style guides

- It is common for style conventions to be brought together into a **style guide**.
- If everyone follows the same style guide, it makes it easier to read code written by others.
  - "Code is read much more often than it is written."
- For Python, we will follow the [PEP 8](https://www.python.org/dev/peps/pep-0008/) style guide.
- It is worth skimming through PEP 8, but here are some highlights:
  - Indent using 4 spaces
  - Have whitespace around operators, e.g. `x = 1` not `x=1`
  - But avoid extra whitespace, e.g. `f(1)` not `f (1)`
  - Single and double quotes both fine for strings, but only use """triple double quotes""", not '''triple single quotes'''
  - Variable and function names use `underscores_between_words`
  - And much more...

#### Automatic style checking

This is not required, but I found it handy to install an automatic PEP 8 formatter. These commands should work; see instructions [here](https://github.com/ryantam626/jupyterlab_code_formatter).

```
pip install autopep8
jupyter labextension install @ryantam626/jupyterlab_code_formatter
pip install jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter
```

In [ ]:
blah = [5, 3, 4, 5, 4]
blah2 = 5
# This code is so great


#### Guidelines that cannot be checked automatically

- Variable names should use underscores (PEP 8), but also need to make sense.
  - e.g. `spin_times` is a reasonable variable name
  - `my_list_of_thingies` adheres to PEP 8 but is NOT a reasonable variable name
  - same for `lst` - fine for explaining a concept, but not as part of a script that will be reused
- DRY (we talked about this last week)
- Magic numbers
- Comments

#### Magic numbers

In [ ]:
# NOT RECOMMENDED BECAUSE "8" IS A MAGIC NUMBER

def num_labs(num_weeks):
    """Compute the number of labs and MDS student attends per week."""
    return num_weeks * 49

In [ ]:
# BETTER

def num_labs(num_weeks, labs_per_week=4):
    """Compute the number of labs and MDS student attends per week."""
    return num_weeks * labs_per_week

In [ ]:
# ALSO FINE

LABS_PER_WEEK = 4 

def num_labs(num_weeks):
    """Compute the number of labs and MDS student attends per week."""
    return num_weeks * LABS_PER_WEEK

- In the above, `LABS_PER_WEEK` is being set as a global constant.
- More on this next class.

So, why avoid magic numbers?

1. They make the code hard to read. Once you give the number a name, the code is much clearer.
2. You may need to use them in multiple places, in which case you'd be violating DRY.


#### Comments

- Comments are important for understanding your code.
- While docstrings cover what a function _does_, your comments will help document _how_ your code achieves its goal.
- There are PEP 8 guidelines on the length, spacing, capitalization of comments.
- But, like variable names, this is not sufficient for a good comment.

Below, here is an example of a reasonable comment:

In [ ]:
def random_walker(T):
    x = 0
    y = 0

    for i in range(T): 
        
        # Generate a random number between 0 and 1.
        # Then, go right, left, up or down if the number
        # is in the interval [0,0.25), [0.25,0.5),
        # [0.5,0.75) or [0.75,1) respectively.
        
        r = random() 
        if r < 0.25:
            x += 1      # Go right
        elif r < 0.5:
            x -= 1      # Go left
        elif r < 0.75:
            y += 1      # Go up
        else:
            y -= 1      # Go down

        print((x,y))

    return x**2 + y**2

Here are some **BAD EXAMPLES** of comments:

In [ ]:
def random_walker(T):
    # intalize cooords
    x = 0
    y = 0

    for i in range(T):  # loop T times
        r = random() 
        if r < 0.25:
            x += 1 # go right
        elif r < 0.5:
            x -= 1 # go left
        elif r < 0.75:
            y += 1 # go up
        else:
            y -= 1

        # Print the location
        print((x,y))

    # In Python, the ** operator means exponentiation.
    return x**2 + y**2

![](https://imgs.xkcd.com/comics/code_quality.png)

## Python debugger (`pdb`) (5 min)

- My Python code doesn't work: what do I do?

In [27]:
def random_walker(T):
    """
    Simulates T steps of a 2D random walk, and prints the result of each step.
    Returns the squared distance from the origin.
    
    Arguments:
    T -- (int) the number of steps to take
    """

    x = 0
    y = 0

    for i in range(T):
        r = random()
        if r < 0.25:
            x += 1
        if r < 0.5:
            x -= 1
        if r < 0.75:
            y += 1
        else:
            y -= 1

        print((x,y))

    return x**2 + y**2

random_walker(10)

(-1, 1)
(-1, 2)
(-1, 3)
(-1, 4)
(-1, 3)
(-2, 4)
(-2, 5)
(-2, 4)
(-3, 5)
(-4, 6)


52

- Looks good, right?
- But wait, why does it always go left? 
- Let's add some `print` statements inside the `if` blocks to see what's going on.
- Alternative: `pdb`

In [32]:
def random_walker(T):
    """
    Simulates T steps of a 2D random walk, and prints the result of each step.
    Returns the squared distance from the origin.
    
    Arguments:
    T -- (int) the number of steps to take
    """

    x = 0
    y = 0

    for i in range(T):
        r = random()
        #print(r)
        
        pdb.set_trace()
        if r < 0.25:
        #    print("I'm going right!")
            x += 1
        if r < 0.5:
        #    print("I'm going left!")
            x -= 1
        if r < 0.75:
            y += 1
        else:
            y -= 1

        print((x,y))

    return x**2 + y**2

random_walker(10)

> /tmp/ipykernel_1549/3516861274.py(18)random_walker()
     16 
     17         pdb.set_trace()
---> 18         if r < 0.25:
     19         #    print("I'm going right!")
     20             x += 1



ipdb>  quit()


See the `pdb` docs [here](https://docs.python.org/3/library/pdb.html).

## Numpy arrays (10 min)

#### Numpy array shapes

A numpy array is sort of like a list:

In [1]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
import numpy as np
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [35]:
type(my_array)

numpy.ndarray

However, unlike a list, it can only hold a single type (usually numbers):

In [41]:
my_list = [1,"hi"]

In [6]:
my_array = np.array((1, "hi"))

In [7]:
my_array

array(['1', 'hi'], dtype='<U21')

Above: it converted the integer `1` into the string `'1'` (just avoid this!).

### Creating arrays

Several ways to create numpy arrays:

In [8]:
x = np.zeros(10) # an array of zeros with size 10
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
x = np.ones(4) # an array of ones with size 4
x

array([1., 1., 1., 1.])

In [11]:
x = np.arange(1,5) # from 1 inclusive to 5 exlcusive
x

array([1, 2, 3, 4])

In [44]:
x = np.arange(1,5,0.5) # step by 0.5
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [15]:
x = np.linspace(1,5,20) # 20 equally spaced points between 1 and 5
x

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [84]:
x = np.random.rand(5) # random numbers uniformly distributed from 0 to 1
x

array([0.0057013 , 0.72725019, 0.37079014, 0.61918229, 0.84647517])

### Elementwise operations

In [18]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [19]:
y = x + 1
y

array([2., 2., 2., 2.])

In [48]:
x - y

array([-1., -1., -1., -1.])

In [49]:
x == y

array([False, False, False, False])

In [ ]:
x * y

In [ ]:
x ** y

In [ ]:
x / y

In [20]:
np.array_equal(x,y)

False

## Array shapes (10 min)

The above are 1-D arrays:

In [26]:
x
x.shape #returns a tuple of the size in each dimension. 

(4,)

Aside: tuples with 1 element

In [ ]:
[1]

In [ ]:
(1)

In [27]:
t = (1,) # tuple with 1 element
t

(1,)

In [28]:
type(t)

tuple

In [29]:
len(x)

4

Just like a list of lists

In [6]:
x = [[1,2],[3,4],[5,6]]
y = np.array(x)
y[2,1]

6

You can have 2-D numpy arrays:

In [4]:
x = np.zeros((3,6))
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [44]:
x.T # transpose


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
x.shape

(3, 6)

In [64]:
x.size # total number of elements

18

In [1]:
import numpy as np
x=np.array([[1],[2]])


x.ndim # len(x.shape)

2

Annoying things:

In [2]:
np.random.rand(3,4) # For random numbers we do not pass a tuple

array([[0.70390502, 0.09178905, 0.90517083, 0.71923763],
       [0.44263572, 0.44016927, 0.83536951, 0.52480367],
       [0.15268353, 0.37259496, 0.23720317, 0.80382035]])

#### "dimension" and "length"

- The word dimension has 2 meanings (not my fault!)
  - We refer to the length of a vector as its dimension, because we think of it as a point in $d$-dimensional space
  - But in terms of being a container holding numbers, it's a 1-dimensional container regardless of its length
  - **Make sure you understand this!** (and see below)

In [61]:
random_walker_location = np.zeros(2)
random_walker_location

array([0., 0.])

In [58]:
random_walker_location.ndim

2

In [90]:
x = np.random.rand(5)
x

array([0.07513306, 0.31637934, 0.81709595, 0.0494117 , 0.56549877])

In [62]:
len(x)

3

- Above: in linear algebra terms, we call this a 5-dimensional vector because it's a point in 5-dimensional space. 
  - But in numpy it's a 1-dimensional array.
  - We could say it's a vector of length 5, but that wouldn't be much better; "length" is also a broken word.
  - It could mean `len(x)` or it could mean $\sqrt{\sum_i x_i^2}$, which is the Euclidean "length" of a vector from linear algebra.
- There is no perfect solution here - just try to be very clear about what you mean and what other people mean.

In [65]:
x = np.random.rand(2,3,4) # a 3-D array
x

array([[[0.70242203, 0.48134598, 0.31663204, 0.32476303],
        [0.70453745, 0.12330934, 0.55798451, 0.10115563],
        [0.05880818, 0.71531826, 0.96802075, 0.49053233]],

       [[0.2822715 , 0.9454485 , 0.69734811, 0.07088311],
        [0.74525088, 0.85890185, 0.22610539, 0.97045839],
        [0.54355031, 0.38738757, 0.08082899, 0.73200058]]])

In [101]:
x.size

24

In [102]:
x

array([[[0.43162126, 0.31721143, 0.3652841 , 0.92466078],
        [0.3414643 , 0.89316888, 0.40674064, 0.5723818 ],
        [0.70740039, 0.03658707, 0.44697157, 0.38884737]],

       [[0.93836741, 0.3462008 , 0.01223981, 0.39180543],
        [0.855577  , 0.79143292, 0.11900243, 0.65914563],
        [0.09322853, 0.15927159, 0.85577003, 0.51439311]]])

In [4]:
table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7,9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
])

In [67]:
table.max()

9

In [5]:
table.max(axis=0) #it performs that max() for each set of values along axis=0.
#table.max(axis=1) #it performs that max() for each set of values along axis=1.

array([5, 6, 7, 9])

**One of the most confusing things about numpy:** what I call a "1-D array" can have 3 possible shapes:

In [75]:
x = np.ones(5)
print(x)
print("size:", x.size)
print("ndim:", x.ndim)
print("shape:",x.shape)

[1. 1. 1. 1. 1.]
size: 5
ndim: 1
shape: (5,)


In [76]:
y = np.ones((1,5))
print(y)
print("size:", y.size)
print("ndim:", y.ndim)
print("shape:",y.shape)

[[1. 1. 1. 1. 1.]]
size: 5
ndim: 2
shape: (1, 5)


In [77]:
z = np.ones((5,1))
print(z)
print("size:", z.size)
print("ndim:", z.ndim)
print("shape:",z.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
size: 5
ndim: 2
shape: (5, 1)


In [78]:
np.array_equal(x,y)

False

In [79]:
np.array_equal(x,z)

False

In [80]:
np.array_equal(y,z)

False

In [81]:
x + y # makes sense

array([[2., 2., 2., 2., 2.]])

In [82]:
y + z # wait, what????

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

Above: this is called "broadcasting" and will be discussed in the next course (DSCI 523).

## Indexing and slicing (10 min)

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
x[3]

3

In [107]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
x[:4]

array([0, 1, 2, 3])

In [7]:
x[2:5]

array([2, 3, 4])

In [8]:
x[2:3]

array([2])

In [ ]:
x[-1]

In [9]:
x[-2]

8

In [10]:
x[5:0:-1]

array([5, 4, 3, 2, 1])

For 2D arrays:

In [11]:
x = np.random.randint(10,size=(4,6))
x

array([[2, 8, 6, 3, 3, 0],
       [8, 0, 6, 0, 6, 8],
       [3, 3, 2, 7, 3, 2],
       [0, 2, 4, 2, 6, 3]])

In [12]:
x[3,4] # do this

6

In [13]:
x[3][4] # i do not like this as much

6

In [14]:
x[3]

array([0, 2, 4, 2, 6, 3])

In [89]:
len(x) # generally, just confusing

4

In [115]:
x.shape

(4, 6)

In [19]:
x[:,2] # column number 2

array([6, 6, 2, 4])

In [20]:
x[2:,:3]

array([[3, 3, 2],
       [0, 2, 4]])

In [92]:
x[1,1] = 555555
x

array([[     6,      2,      8,      1,      5,      7],
       [     9, 555555,      8,      9,      1,      7],
       [     1,      6,      3,      7,      9,      3],
       [     1,      8,      8,      1,      4,      9]])

#### Boolean indexing

In [101]:
x = np.random.rand(10)
x

array([0.48534035, 0.63527225, 0.74718817, 0.29110079, 0.72998648,
       0.50111713, 0.22788109, 0.34036319, 0.019074  , 0.66411154])

In [102]:
x + 1
x

array([0.48534035, 0.63527225, 0.74718817, 0.29110079, 0.72998648,
       0.50111713, 0.22788109, 0.34036319, 0.019074  , 0.66411154])

In [103]:
## Masking: A mask is an array that has the exact same shape as your data, but instead of your values, it holds Boolean values: either True or False.
x_thresh = x > 0.5
x_thresh

array([False,  True,  True, False,  True,  True, False, False, False,
        True])

In [104]:
x[x_thresh]

array([0.63527225, 0.74718817, 0.72998648, 0.50111713, 0.66411154])

In [105]:
#Boolean indexing
x[x_thresh] = 0.5 # set all elements  > 0.5 to be equal to 0.5
x

array([0.48534035, 0.5       , 0.5       , 0.29110079, 0.5       ,
       0.5       , 0.22788109, 0.34036319, 0.019074  , 0.5       ])

In [21]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])


In [22]:
np.sort(square)

array([[ 2,  3, 13, 16],
       [ 5,  8, 10, 11],
       [ 6,  7,  9, 12],
       [ 1,  4, 14, 15]])

In [24]:
np.sort(square, axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [23]:
np.sort(square, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [16, 15, 14, 13]])

In [26]:
# Concatenation
a = np.array([
    [4, 8],
    [6, 1]
])

b = np.array([
    [3, 5],
    [7, 2]
])

In [118]:
np.hstack((a, b))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [119]:
np.vstack((b,a))

array([[3, 5],
       [7, 2],
       [4, 8],
       [6, 1]])

In [31]:
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [30]:
 np.concatenate((a, b), axis=0)

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])